GET {{url}}/hotel
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/hotel/1
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/hotel/1/room
Authorization: Bearer {{jwt_token}}

###
POST {{url}}/hotel
Authorization: Bearer {{jwt_token}}

{
    "name": "Hotel 4",
    "address": "Address 4"
}

###
POST {{url}}/hotel
Authorization: Bearer {{jwt_token}}

{
    "name": "Hotel 3",
}

###
POST {{url}}/hotel
Authorization: Bearer {{jwt_token}}

{
    "badname": "Bad",
    "badaddress": "Bad"
}

###
PUT {{url}}/hotel/1
Authorization: Bearer {{jwt_token}}

{
    "name": "New Hotel Name",
    "address": "New Hotel Address"
}

###
DELETE {{url}}/hotel/1
Authorization: Bearer {{jwt_token}}