GET localhost:7070/api/hotel
Authorization: Bearer {{jwt_token}}

###
GET localhost:7070/api/hotel/1
Authorization: Bearer {{jwt_token}}

###
GET localhost:7070/api/hotel/1/room
Authorization: Bearer {{jwt_token}}

###
POST localhost:7070/api/hotel
Authorization: Bearer {{jwt_token}}

{
    "name": "Hotel 4",
    "address": "Address 4"
}

###
POST localhost:7070/api/hotel
Authorization: Bearer {{jwt_token}}

{
    "name": "Hotel 3",
}

###
POST localhost:7070/api/hotel
Authorization: Bearer {{jwt_token}}

{
    "badname": "Bad",
    "badaddress": "Bad"
}

###
PUT localhost:7070/api/hotel/1
Authorization: Bearer {{jwt_token}}

{
    "name": "New Hotel Name",
    "address": "New Hotel Address"
}

###
DELETE localhost:7070/api/hotel/1
Authorization: Bearer {{jwt_token}}